# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: 'P'
    source: 'PreReq'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo $(resources.pipeline.P.pipelineID)
    echo $(resources.pipeline.P.runName)
    echo $(resources.pipeline.P.runID)
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
