# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
  - pipeline: 'P'
    source: 'PreReq'
    project: epceylon

stages:
- stage: 'Verification'
  pool:
    vmImage: 'ubuntu-latest'

  jobs:
  - deployment: 'VerifyVariables'
    environment: 'Dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo $(resources.pipeline.P.pipelineID)
              echo $(resources.pipeline.P.runName)
              echo $(resources.pipeline.P.runID)
              echo $(Build.Reason)
              echo See https://aka.ms/yaml
              buildSource=$(Build.SourceBranch)
              echo Branch $(Build.SourceBranch)
              tag=${buildSource#*tags/}
              echo $tag
            displayName: 'Run a multi-line script'
