parameters:
- name: ProjectName
  type: string
- name: BuildNumber
  type: string
- name: Cluster
  type: string
- name: TestObj
  type: object
  default: |
    list:
    - API.A
    - API.B
    - API.C

steps:
- script: |
    cat > ce-apis.py << EOL
    import sys

    proj = sys.argv[1]
    paths = proj.lower().split(".")

    apiName = "-".join(paths)
    print("##vso[task.setvariable variable=ApiName]%s" %apiName)
    print("##vso[task.setvariable variable=TargetProject]%s" %proj)
    EOL
  displayName: "Write ECR Name Generator"

- ${{ each item in parameters.TestObj.list }}
  - task: PythonScript@0
    displayName: 'ParamTest'
    inputs:
      scriptSource: 'filePath'
      scriptPath: 'test.py'
      arguments: '${{ item }}'
    
- script: |
    PROJ=${{ parameters.ProjectName }}
    API_NAME="$(echo ${PROJ//\./-} | awk '{print tolower($0)}')"
    IMG_TAG=${{ parameters.BuildNumber }}
    echo "Deploying ${API_NAME}:${IMG_TAG} to ${Cluster}"